INSERT INTO STUDENT(NAME, DEPARTMENT,COURSE) VALUES('sridhar','Chemistry','NEET');
INSERT INTO STUDENT(NAME, DEPARTMENT,COURSE) VALUES('hari','Physics','IAS');
INSERT INTO STUDENT(NAME, DEPARTMENT,COURSE) VALUES('Krithik','Maths','NEET');
INSERT INTO STUDENT(NAME, DEPARTMENT,COURSE) VALUES('Pravin','Botany','NEET');
INSERT INTO STUDENT(NAME, DEPARTMENT,COURSE) VALUES('Kumar','Zoology','IAS');

INSERT INTO GAMES VALUES(1,"Cricket",1);
INSERT INTO GAMES VALUES(2,"Football",1);
INSERT INTO GAMES VALUES(3,"Hockey",5);
INSERT INTO GAMES VALUES(4,"Tennis",3);

INSERT INTO COURSE VALUES(1,"NEET",1);
INSERT INTO COURSE VALUES(2,"IAS",2);
INSERT INTO COURSE VALUES(2,"IAS",3);
INSERT INTO COURSE VALUES(1,"NEET",4);
INSERT INTO COURSE VALUES(2,"IAS",5);
