CREATE TABLE STUDENT
(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
DEPARTMENT VARCHAR(30) NOT NULL
);

CREATE TABLE GAMES(
GAMEID INT PRIMARY KEY,
GAMENAME VARCHAR(30)
);